name: newproject
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  fluttertoast: ^2.0.7
  shared_preferences: "^0.4.2"


 
  
  carousel_pro: ^0.0.13


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - image/test.jpg
   - image/potato.jpg
   - image/sandwitch.jpg
   - image/fish.jpg
   - image/chicken.jpg
   - image/grains.jpg
   - image/drinks.jpg
   - image/chickn2.jpeg
   - image/chickenfrize.jpeg
   - image/chicken3.jpg
   - image/cart.png
   - image/chipsy.jpg
   - image/alban.jpg
   - image/cosmt.jpg
   - image/chickens/download (4).jpg
   - image/chickens/Frozen-tilapia-fish-fillet-no-skin-for.jpg
   - image/chickens/images (1).jpg
   - image/chickens/images (2).jpg
   - image/chickens/images (3).jpg
   - image/chickens/images (4).jpg
   - image/chickens/images (5).jpg
   - image/chickens/images (6).jpg
   - image/chickens/images (7).jpg
   - image/chickens/images (8).jpg
   - image/chickens/images (9).jpg
   - image/chickens/images.jpg
   - image/chickens/pngtree-frozen-beef-png-clipart_2349780.jpg
   - image/chickens/SENPILIC_KATALOG_1609_BASKI-2014-40.jpg
   - image/grains/100405410.jpg
   - image/grains/CANNED-SOUPS-FROM-FRESH-VEGETABLES.jpg
   - image/grains/download (1).jpg
   - image/grains/download (2).jpg
   - image/grains/download (3).jpg
   - image/grains/download (4).jpg
   - image/grains/download (5).jpg
   - image/grains/download (9).jpg
   - image/grains/download (10).jpg
   - image/grains/download.jpg
   - image/grains/images (1).jpg
   - image/grains/images (24).jpg
   - image/grains/adas.jpg
   - image/grains/Red-split-lentils.jpg

   - image/drinks/download (1).jpg
   - image/drinks/download (5).jpg
   - image/drinks/download (12).jpg
   - image/drinks/download (13).jpg
   - image/drinks/download.jpg
   - image/drinks/images (1).jpg
   - image/drinks/images (12).jpg
   - image/drinks/images (13).jpg
   - image/drinks/images (15).jpg
   - image/chickens/shopping.jpg


 
   



     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
